import Navbar from 'components/Navbar';

// Styles
import './css/sass/main.scss';
import './css/globals.css';

import { Inter } from 'next/font/google';
import { NextAuthSessionProvider } from './providers/sessionProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function renderChildrenWithNavBar(children, containerClasses = 'max-w-6xl mx-auto') {
  return (<div className={containerClasses}>
    <Navbar />
    {children}
  </div>
  )
}

function renderChildren(children) {
  return (<>{children}</>)
}

function dontShowNavNavBarIn(page) {
  const exceptions = ['signIn', 'signUp'];
  return exceptions.includes(page);
}

export default function RootLayout({ children }) {

  const childrenSegment = children?.props.childProp?.segment;

  return (
    <html lang="en">
      <body className={`${inter.className} sm:overflow-x-hidden`}>
        <NextAuthSessionProvider>
          {
            dontShowNavNavBarIn(childrenSegment)
              ? renderChildren(children)
              : renderChildrenWithNavBar(children)
          }
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
