import Navbar from '@/components/Navbar';

// Styles
import './css/sass/main.scss';
import './css/globals.css';

import { Inter } from 'next/font/google';
import { NextAuthSessionProvider } from './providers/sessionProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MyInvest',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body>
          <NextAuthSessionProvider>
            <div>
              <Navbar />
              {children}
            </div>
          </NextAuthSessionProvider>
        </body>
      </html>
  )
}
